### ISSUE TITLE
Release process improvements from https://github.com/GaloisInc/saw-script/tree/release-0.8

### ISSUE THREAD

**Issue by ldettwy** [GaloisInc/cryptol#1175]
- Exclude yasm
- Remove setup skip branches in .github/ci.sh
- `cron: "0 10 * * *" # 10am UTC -> 2/3am PST`
- Standardize config parameters and logic
- Implement release conditions:
  - `[[ "refs/heads/release-$(.github/ci.sh ver)" == "${{ github.event.ref }}" ]]`
  - `[[ "refs/heads/release-$(git describe --tags --abbrev=0)" == "${{ github.event.ref }}" ]]`
- Don't have a separate bundle step
- Container image push logic
  ```yaml
   - if: needs.config.outputs.event-schedule == 'true'
     name: ${{ matrix.image }}:nightly
     run: |
       docker tag ${{ matrix.image }}:$COMMON_TAG ${{ matrix.image }}:nightly
       docker push ${{ matrix.image }}:nightly
   - if: needs.config.outputs.release == 'true'
     name: ${{ matrix.image }}:${{ needs.config.outputs.version }}
     run: |
       docker tag ${{ matrix.image }}:$COMMON_TAG ${{ matrix.image }}:${{ needs.config.outputs.version }}
       docker push ${{ matrix.image }}:${{ needs.config.outputs.version }}
       docker tag ${{ matrix.image }}:$COMMON_TAG ${{ matrix.image }}:latest
       docker push ${{ matrix.image }}:latest
  ```
