### ISSUE TITLE
Merging new commits to master causes numerous CI cache misses

### ISSUE THREAD

**Issue by emlisa3162** [GaloisInc/cryptol#1209]
Building HEAD of master takes a long time when there are significant cache misses. This mostly affects macOS and docker image building. When a change is merged that causes cache misses in master, these misses also arise in subsequent rebuilds of pull requests even if they haven't been rebased/updated since. Some things that can be done about this:

- [ ] Additionally use the git merge-base as a cache key, which remains fixed if the pull request remains fixed:
  ```yaml
  - id: merge-base
    shell: bash
    run: |
      MERGE_BASE=$(git merge-base ${{ github.head_ref }} ${{ github.base_ref }})
      echo "::set-output name=ref::$MERGE_BASE"
  - uses: actions/cache@v2
    key: ${{ github.head_ref }}
    restore-keys: |
      ${{ steps.merge-base.outputs.ref }}
      ${{ github.base_ref }})
  ```
- [ ] Generate build cache for master faster (`on: push: master`), i.e., significantly reign-in compile times
