### ISSUE TITLE
release Cryptol as a Galois-signed macOS binary

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/cryptol#992]
We should not be forcing users to jump through insecure hoops to install our releases.

See https://developer.apple.com/developer-id/

**Comment by atomb** [comment]
I can confirm that we're discussing how to make this happen. I expect 2021 releases to be properly signed.

**Comment by LisannaAtGalois** [comment]
https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/ might be useful here

**Comment by RyanGlScott** [comment]
Do note that there is a workaround that one can apply after downloading a Cryptol bindist on macOS: 

```
$ xattr -rc $path_to_extracted_cryptol_bindist_directory
```

Also note that this is only really required if you are downloading Cryptol from a web browser (e.g., Safari). Other download methods (e.g., `wget`, `curl`, the Docker images on ghcr.io, etc.) don't suffer from this issue, as far as I can tell.

See also [this long thread](https://gitlab.haskell.org/ghc/ghc/-/issues/17418) on GHC's exploration into how to notarize things in CI. **tl;dr** it's pretty complicated.

**Comment by RyanGlScott** [comment]
After some experimentation, I've more-or-less figured out how to do this reliably as part of a CI job. I'll write down some notes here to lay out roughly what needs to be done:

* Create a Galois-specific Apple signing certificate and notarization key. (We have done this part.)
* In CI, import the signing certificate with something like:

  ```yaml
      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_P12_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_P12_PASSWORD }}
  ```

  Where `${{ secrets* }}` correspond to GitHub secret values.
* In CI, after compiling each binary, it needs to be signed with something like:

  ```yaml
      - name: Sign binary
        env:
          IDENTITY_NAME: ${{ secrets.APPLE_P12_IDENTITY_NAME }}
        run: |
          codesign \
            --force \
            --options runtime \
            --sign "$IDENTITY_NAME" \
            <path-to-binary-1> ... <path-to-binary-n>
  ```
* Apple only allows notarizing binaries if they're part of a `.dmg`, `.app`, or `.zip` file. We aren't using the former two file formats to distribute Cryptol, so the best bet is to create a temporary `.zip` file in CI for notarization purposes:

  ```yaml
      - name: Zip binaries for notarization
        run: |
          zip binaries-to-notarize.zip <path-to-binary-1> ... <path-to-binary-n>
  ```
* In CI, notarize the binaries with:

  ```yaml
      - name: Notarize binary
        env:
          KEY_ID: ${{ secrets.APPLE_P8_KEY_ID }}
          ISSUER_ID: ${{ secrets.APPLE_P8_ISSUER_ID }}
          API_KEY: ${{ secrets.APPLE_P8_API_KEY }}
        run: |
          echo "$API_KEY" > "AuthKey_$KEY_ID.p8"
          xcrun notarytool submit binaries-to-notarize.zip \
            --key "AuthKey_$KEY_ID.p8" \
            --key-id "$KEY_ID" \
            --issuer "$ISSUER_ID" \
            --wait
  ```

  This step is fairly time-consuming, as it requires uploading the binaries to Apple's notarization server. Moreover, Apple recommends [limiting notarizations to 75 per day](https://developer.apple.com/documentation/security/customizing-the-notarization-workflow#Avoid-long-notarization-response-times-and-size-limits). As such, we should probably only perform this step in limited contexts (e.g., only in release or nightly CI workflows). 

That's the game plan. The remaining steps are to rework the CI in Cryptol (this issue), SAW (https://github.com/GaloisInc/saw-script/issues/809), Crux (https://github.com/GaloisInc/crucible/issues/1827), and `what4-solvers` (https://github.com/GaloisInc/what4-solvers/issues/86).
